version: '3'
services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: hello-mysql
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_HOST=127.0.0.1:3306"
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=homePage"
      - "TZ=Asia/Shanghai"

  web:
    build: ./backend
    depends_on:
      - mysql
    environment:
      - "DB_USER=root"
      - "DB_PASSWORD=123456"
      - "DB_HOST=mysql:3306"
      - "DB_NAME=homePage"
    links:
      - mysql:mysql
    ports:
      - 8080:8080
    command: "/usr/local/bin/backend"